services:
  udv-benefits:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000 --workers 4 --log-level info --proxy-headers --timeout-keep-alive 0"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - image_folder:/udv-benefits-collection/files/benefit_covers
      - files_folder:/udv-benefits-collection/files/receipts
    security_opt:
      - apparmor=unconfined
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 1m
      timeout: 30s
      retries: 5

  postgres:
    env_file:
      - .env
    container_name: postgres_db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_home:
    external: false
  image_folder:
    external: false
  files_folder:
    external: false

