"""add additional_info column

Revision ID: 3d0f6b2ea58d
Revises: 5becbe9465da
Create Date: 2024-11-29 19:00:02.930615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0f6b2ea58d'
down_revision: Union[str, None] = '5becbe9465da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_benefit_relation', sa.Column('additional_info', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_constraint('user_benefit_relation_benefit_id_fkey', 'user_benefit_relation', type_='foreignkey')
    op.create_foreign_key(None, 'user_benefit_relation', 'benefit', ['benefit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_benefit_relation', type_='foreignkey')
    op.create_foreign_key('user_benefit_relation_benefit_id_fkey', 'user_benefit_relation', 'benefit', ['benefit_id'], ['id'])
    op.drop_column('user_benefit_relation', 'additional_info')
    # ### end Alembic commands ###
