"""create user_info table

Revision ID: 8acc903f161e
Revises: b86900d7b098
Create Date: 2024-10-26 10:03:42.078729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import text

from src.config import ADMIN_EMAIL


# revision identifiers, used by Alembic.
revision: str = '8acc903f161e'
down_revision: Union[str, None] = 'b86900d7b098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info_table',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('place_of_employment', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('employment_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    result = op.get_bind().execute(text("SELECT id FROM \"user\" WHERE email = :email"), {"email": ADMIN_EMAIL})
    admin_id = result.fetchone()[0]
    op.execute(f"INSERT INTO \"user_info_table\" (user_id) VALUES ('{admin_id}')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info_table')
    # ### end Alembic commands ###
