"""add benefits and categories tables

Revision ID: b86900d7b098
Revises: b7ed5ee767a9
Create Date: 2024-10-19 21:51:47.529972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b86900d7b098'
down_revision: Union[str, None] = 'b7ed5ee767a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
                    sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
                    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('cover_path', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
                    sa.Column('categories', postgresql.ARRAY(sa.Integer()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
                    sa.Column('availability_interval', sa.Interval(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.execute(
        """INSERT INTO category VALUES 
        (1, 'до 3 месяцев', '3 months'), 
        (2, 'до 1 года', '1 year'), 
        (3, 'до 3 лет', '3 years'), 
        (4, 'больше 3 лет', '3 years')""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('benefit')
    # ### end Alembic commands ###
